name: Build Go Project for macOS ARM64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos-arm64:
    runs-on: ubuntu-latest  # The runner OS doesn't matter for cross-compilation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Change to match your Go version

      - name: Build for macOS ARM64
        run: |
          cd goRadio
          GOOS=darwin GOARCH=arm64 go build -o goRadio-macos-arm64
